name: Create New Dev Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to create
        required: true

jobs:
  create_release_branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get base branch
        id: get_base_branch
        run: echo "GIT_BASE_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Update version file
        run: |
          echo "${{ github.event.inputs.version }}" > version.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Release ${{ github.event.inputs.version }}"
          branch: release-${{ github.event.inputs.version }}
          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'
          repository: .
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: true
          skip_fetch: true    
          skip_checkout: true
          create_branch: true
      - name: Open the pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-${{ github.event.inputs.version }}
          base: ${{ steps.get_base_branch.outputs.GIT_BASE_BRANCH }}
      - name: Open a new dev release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.event.inputs.version }}-dev
          tag_name: ${{ github.event.inputs.version }}-dev
          target_commitish: release-${{ github.event.inputs.version }}
          draft: true
