name: Test trigger with comment on pr

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  propagate:
    runs-on: ubuntu-22.04
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/propagate'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.t
